#Sample YML file to configure profiles and log4j2 config pattern files for different environments - local , dev, prod
spring:
  profiles:
    active: local
  application:
    name: spring-log4j2
  main:
    banner-mode: off

---

spring:
  profiles: local
server:
  port: 8090
logging:
  config: classpath:log4j2-local.xml

---

spring:
  profiles: dev
server:
  port: 9090
logging:
  config: classpath:log4j2-dev.xml

---

spring:
  profiles: prod
server:
  port: 8081
logging:
  config: classpath:log4j2-prod.xml